FROM crazymax/xgo:base

ENV GO_VERSION 186

RUN \
  export ROOT_DIST=https://storage.googleapis.com/golang/go1.8.6.linux-amd64.tar.gz     && \
  export ROOT_DIST_SHA=f558c91c2f6aac7222e0bd83e6dd595b8fac85aaa96e55d15229542eb4aaa1ff && \
  \
  $BOOTSTRAP_PURE
