FROM crazymax/xgo:base

ENV GO_VERSION 1136

RUN \
  export ROOT_DIST=https://storage.googleapis.com/golang/go1.13.6.linux-amd64.tar.gz      && \
  export ROOT_DIST_SHA=a1bc06deb070155c4f67c579f896a45eeda5a8fa54f35ba233304074c4abbbbd && \
  \
$BOOTSTRAP_PURE
