FROM crazymax/xgo:base

ENV GO_VERSION 1112

RUN \
  export ROOT_DIST=https://storage.googleapis.com/golang/go1.11.2.linux-amd64.tar.gz    && \
  export ROOT_DIST_SHA=1dfe664fa3d8ad714bbd15a36627992effd150ddabd7523931f077b3926d736d && \
  \
$BOOTSTRAP_PURE
