FROM crazymax/xgo:base

ENV GO_VERSION 164

RUN \
  export ROOT_DIST=https://storage.googleapis.com/golang/go1.6.4.linux-amd64.tar.gz     && \
  export ROOT_DIST_SHA=b58bf5cede40b21812dfa031258db18fc39746cc0972bc26dae0393acc377aaf && \
  \
  $BOOTSTRAP_PURE
