FROM crazymax/xgo:base

ENV GO_VERSION 195

RUN \
  export ROOT_DIST=https://storage.googleapis.com/golang/go1.9.5.linux-amd64.tar.gz     && \
  export ROOT_DIST_SHA=d21bdabf4272c2248c41b45cec606844bdc5c7c04240899bde36c01a28c51ee7 && \
  \
  $BOOTSTRAP_PURE
