FROM crazymax/xgo:base

ENV GO_VERSION 11315

RUN \
  export ROOT_DIST=https://storage.googleapis.com/golang/go1.13.15.linux-amd64.tar.gz    && \
  export ROOT_DIST_SHA=01cc3ddf6273900eba3e2bf311238828b7168b822bb57a9ccab4d7aa2acd6028  && \
  \
$BOOTSTRAP_PURE
