FROM crazymax/xgo:base

ENV GO_VERSION 1103

RUN \
  export ROOT_DIST=https://storage.googleapis.com/golang/go1.10.3.linux-amd64.tar.gz    && \
  export ROOT_DIST_SHA=fa1b0e45d3b647c252f51f5e1204aba049cde4af177ef9f2181f43004f901035 && \
  \
  $BOOTSTRAP_PURE
