FROM crazymax/xgo:base

ENV GO_VERSION 192

RUN \
  export ROOT_DIST=https://storage.googleapis.com/golang/go1.9.2.linux-amd64.tar.gz     && \
  export ROOT_DIST_SHA=de874549d9a8d8d8062be05808509c09a88a248e77ec14eb77453530829ac02b && \
  \
  $BOOTSTRAP_PURE
