# Go cross compiler (xgo): Wildcard layer to the latest Go release
# Copyright (c) 2017 Péter Szilágyi. All rights reserved.
# Copyright (c) 2019 CrazyMax
#
# Released under the MIT license.

FROM crazymax/xgo:1.13.x
