FROM crazymax/xgo:base

ENV GO_VERSION 197

RUN \
  export ROOT_DIST=https://storage.googleapis.com/golang/go1.9.7.linux-amd64.tar.gz     && \
  export ROOT_DIST_SHA=88573008f4f6233b81f81d8ccf92234b4f67238df0f0ab173d75a302a1f3d6ee && \
  \
  $BOOTSTRAP_PURE
