FROM crazymax/xgo:base

ENV GO_VERSION 182

RUN \
  export ROOT_DIST=https://storage.googleapis.com/golang/go1.8.2.linux-amd64.tar.gz     && \
  export ROOT_DIST_SHA=5477d6c9a4f96fa120847fafa88319d7b56b5d5068e41c3587eebe248b939be7 && \
  \
  $BOOTSTRAP_PURE
