FROM crazymax/xgo:base

ENV GO_VERSION 187

RUN \
  export ROOT_DIST=https://storage.googleapis.com/golang/go1.8.7.linux-amd64.tar.gz     && \
  export ROOT_DIST_SHA=de32e8db3dc030e1448a6ca52d87a1e04ad31c6b212007616cfcc87beb0e4d60 && \
  \
  $BOOTSTRAP_PURE
