FROM crazymax/xgo:base

ENV GO_VERSION 176

RUN \
  export ROOT_DIST=https://storage.googleapis.com/golang/go1.7.6.linux-amd64.tar.gz     && \
  export ROOT_DIST_SHA=ad5808bf42b014c22dd7646458f631385003049ded0bb6af2efc7f1f79fa29ea && \
  \
  $BOOTSTRAP_PURE
