FROM crazymax/xgo:base

ENV GO_VERSION 185

RUN \
  export ROOT_DIST=https://storage.googleapis.com/golang/go1.8.5.linux-amd64.tar.gz     && \
  export ROOT_DIST_SHA=4f8aeea2033a2d731f2f75c4d0a4995b357b22af56ed69b3015f4291fca4d42d && \
  \
  $BOOTSTRAP_PURE
