FROM crazymax/xgo:base

ENV GO_VERSION 196

RUN \
  export ROOT_DIST=https://storage.googleapis.com/golang/go1.9.6.linux-amd64.tar.gz     && \
  export ROOT_DIST_SHA=d1eb07f99ac06906225ac2b296503f06cc257b472e7d7817b8f822fe3766ebfe && \
  \
  $BOOTSTRAP_PURE
