FROM crazymax/xgo:base

ENV GO_VERSION 1108

RUN \
  export ROOT_DIST=https://storage.googleapis.com/golang/go1.10.8.linux-amd64.tar.gz    && \
  export ROOT_DIST_SHA=d8626fb6f9a3ab397d88c483b576be41fa81eefcec2fd18562c87626dbb3c39e && \
  \
  $BOOTSTRAP_PURE
