name: go-1.9

on:
  pull_request:
    branches:
      - 'master'
    paths:
      - '.github/workflows/go-1.9.yaml'
      - 'docker/go-1.9/**'
  push:
    branches:
      - master
    paths:
      - '.github/workflows/go-1.9.yaml'
      - 'docker/go-1.9/**'
    tags:
      - 'go-1.9-*'

jobs:
  docker:
    strategy:
      matrix:
        go_version:
          - 1.9.0
          - 1.9.1
          - 1.9.2
          - 1.9.3
          - 1.9.4
          - 1.9.5
          - 1.9.6
          - 1.9.7
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Get Latest
        run: |
          echo "##[set-env name=LATEST;]$(cat docker/go-1.9/latest)"
      -
        name: Docker Build
        run: |
          docker build \
            --tag "crazymax/xgo:${{ matrix.go_version }}" \
            --file ./docker/go-1.9/go-${{ matrix.go_version }}/Dockerfile \
            ./docker/go-1.9/go-${{ matrix.go_version }}
          if [ "$LATEST" == "${{ matrix.go_version }}" ]; then
            docker tag "crazymax/xgo:${{ matrix.go_version }}" "crazymax/xgo:1.9.x"
          fi
      -
        name: Docker Login
        if: success() && startsWith(github.ref, 'refs/tags/go-1.9-')
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username crazymax --password-stdin
      -
        name: Docker Push
        if: success() && startsWith(github.ref, 'refs/tags/go-1.9-')
        run: |
          docker image rm crazymax/xgo:base
          docker push crazymax/xgo
      -
        name: Clear
        if: always()
        run: |
          rm -f ${HOME}/.docker/config.json
