name: image

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

on:
  schedule:
    - cron: '0 8 */6 * *'
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/.build.yml
    permissions:
      contents: read # same as global permissions
      packages: write # required to push to GHCR
    strategy:
      fail-fast: false
      matrix:
        go_version:
          - "1.24.0"
          - "1.24.1"
          - "1.24.2"
          - "1.24.3"
          - "1.24.4"
          - "1.24.5"
          - "1.24.6"
          - "1.24.7"
          - "1.25.0"
          - "1.25.1"
    with:
      go_version: ${{ matrix.go_version }}
      latest_current: "1.25.1"
      latest_previous: "1.24.7"
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
