name: test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go_version:
          - 1.25.13
          - 1.26.6
        case:
          - c
          - cpp
          - foundation
          - gopath
          - gorm
          - ffmerger
    steps:
      -
        name: Build xgo
        uses: docker/bake-action@018cb6412ab401ebaa809aa5f85966b74628600f # v7.4.0
        with:
          targets: image
          set: |
            *.tags=xgo:${{ matrix.go_version }}
            *.args.GO_VERSION=${{ matrix.go_version }}
            *.output=type=docker
            *.cache-from=type=gha,scope=go-${{ matrix.go_version }}-linux-amd64
      -
        name: Test ${{ matrix.case }} for go ${{ matrix.go_version }}
        uses: docker/bake-action@018cb6412ab401ebaa809aa5f85966b74628600f # v7.4.0
        with:
          targets: test-${{ matrix.case }}
        env:
          BASE_IMAGE: xgo:${{ matrix.go_version }}
